name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - run: brew style --formula Formula/tuistore.rb
      - run: brew audit --formula --online Formula/tuistore.rb
      - run: brew install --formula Formula/tuistore.rb
      - run: brew test tuistore
